Next time husky commit style =)
Sl4ck3r2/Atestat pull request #6
Opened 2023-01-14 11:37 UTC by Sl4ck3r2

2023-01-16 15:28 UTC, ducaOvidiu commented on frontend/src/components/users-table/index.tsx
> +      <UserDataPopup open={isModalOpen} onOk={() => handleOk()} onCancel={() => handleCancel()} />
`<UserDataPopup open={isModalOpen} onOk={handleOk} onCancel={handleCancel} />`

2023-01-16 15:28 UTC, ducaOvidiu commented
Please change commit style is not something funny

2023-01-19 10:31 UTC, ducaOvidiu requested changes

2023-01-19 10:31 UTC, ducaOvidiu commented on frontend/src/components/bottom-menu/index.module.scss
> +
You don t need space here

2023-01-19 10:31 UTC, ducaOvidiu commented on frontend/src/components/superadmin-menu/index.module.scss
> +
Also here

2023-01-19 10:31 UTC, ducaOvidiu commented on frontend/src/components/user-menu/index.module.scss
> +
Space here is not requierd

2023-01-19 10:31 UTC, ducaOvidiu commented on frontend/src/components/users-table/index.tsx
> +  console.log(data);
You don t need to push console.log into dev it is just for testing

2023-01-19 10:31 UTC, ducaOvidiu commented on frontend/src/pages/dashboard/all-users/all-users.tsx
> +      console.log(response.data);
You have console.log(here)

2023-01-19 18:01 UTC, Ovyzz approved these changes

2023-01-19 18:01 UTC, merged